name: Run Postman API Collection

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:  # Schedule the workflow
    - cron: '0 8,20 * * *'  # Runs at 08:00 and 20:00 UTC daily

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Newman and HTMLExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  # Ensure htmlextra reporter is installed

      - name: Run Postman Collection
        run: newman run Demo_test.postman_collection.json -r htmlextra --reporter-htmlextra-export ./reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: newman-report
          path: ./reports/report.html




